#ifndef EDGEFIRST_HAL_H
#define EDGEFIRST_HAL_H

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @file hal.h
 * @brief EdgeFirst HAL C API
 *
 * SPDX-License-Identifier: Apache-2.0
 * Copyright (c) 2025 Au-Zone Technologies. All Rights Reserved.
 *
 * C API for EdgeFirst Hardware Abstraction Layer providing:
 * - Zero-copy tensor operations with DMA/SHM support
 * - Hardware-accelerated image processing (G2D, OpenGL, CPU)
 * - ML model output decoding (YOLO, ModelPack)
 * - Multi-object tracking (ByteTrack)
 *
 * @section error_handling Error Handling
 * Functions returning int: 0 on success, -1 on error (errno set)
 * Functions returning pointers: valid pointer on success, NULL on error (errno set)
 *
 * @section memory_management Memory Management
 * - hal_*_new() functions transfer ownership to caller (must call hal_*_free())
 * - hal_*_get_*() functions returning pointers are borrowed (valid during parent lifetime)
 * - hal_*_clone_fd() creates new owned fd (caller must close())
 * - hal_*_from_fd() takes ownership of fd (caller must NOT close())
 *
 * @section thread_safety Thread Safety
 * - All functions are thread-safe unless documented otherwise
 * - Tensor map operations require external synchronization when used concurrently
 */


/* Generated with cbindgen:0.29.2 */

/* WARNING: This file is auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include "stdint.h"
#include "stddef.h"
#include "stdbool.h"

/**
 * Output type for model tensor outputs.
 *
 * Identifies the role of a model output tensor in the decoder pipeline.
 *
 * @see hal_decoder_params_add_output
 */
typedef enum HalOutputType {
  /**
   * Combined detection output (e.g. YOLO fused [batch, features, boxes])
   */
  HAL_OUTPUT_TYPE_DETECTION = 0,
  /**
   * Split boxes output [batch, coords, boxes]
   */
  HAL_OUTPUT_TYPE_BOXES = 1,
  /**
   * Split scores output [batch, classes, boxes]
   */
  HAL_OUTPUT_TYPE_SCORES = 2,
  /**
   * Prototype masks for instance segmentation [batch, protos, H, W]
   */
  HAL_OUTPUT_TYPE_PROTOS = 3,
  /**
   * Segmentation mask output
   */
  HAL_OUTPUT_TYPE_SEGMENTATION = 4,
  /**
   * Mask coefficients for instance segmentation
   */
  HAL_OUTPUT_TYPE_MASK_COEFFICIENTS = 5,
  /**
   * Raw mask output
   */
  HAL_OUTPUT_TYPE_MASK = 6,
  /**
   * Class indices for end-to-end split models [batch, N, 1]
   */
  HAL_OUTPUT_TYPE_CLASSES = 7,
} HalOutputType;

/**
 * Decoder framework type.
 *
 * Identifies the model framework that produced the output tensors.
 *
 * @see hal_decoder_params_add_output
 */
typedef enum HalDecoderType {
  /**
   * Ultralytics YOLO models (YOLOv5, YOLOv8, YOLO11, YOLO26)
   */
  HAL_DECODER_TYPE_ULTRALYTICS = 0,
  /**
   * Au-Zone ModelPack models
   */
  HAL_DECODER_TYPE_MODEL_PACK = 1,
} HalDecoderType;

/**
 * Named dimension for tensor shapes.
 *
 * Assigns a semantic name to each dimension in a tensor shape, allowing the
 * decoder to handle different tensor layouts (NCHW vs NHWC, etc.).
 *
 * Pass an array of these alongside shape values in
 * `hal_decoder_params_add_output()`, or pass NULL for unnamed shapes.
 *
 * @see hal_decoder_params_add_output
 */
typedef enum HalDimName {
  /**
   * Batch dimension
   */
  HAL_DIM_NAME_BATCH = 0,
  /**
   * Height spatial dimension
   */
  HAL_DIM_NAME_HEIGHT = 1,
  /**
   * Width spatial dimension
   */
  HAL_DIM_NAME_WIDTH = 2,
  /**
   * Number of object classes
   */
  HAL_DIM_NAME_NUM_CLASSES = 3,
  /**
   * Number of features (e.g. 4 box coords + num_classes + mask_coeffs)
   */
  HAL_DIM_NAME_NUM_FEATURES = 4,
  /**
   * Number of detection boxes / proposals
   */
  HAL_DIM_NAME_NUM_BOXES = 5,
  /**
   * Number of prototype masks
   */
  HAL_DIM_NAME_NUM_PROTOS = 6,
  /**
   * Number of anchors multiplied by features (ModelPack split)
   */
  HAL_DIM_NAME_NUM_ANCHORS_X_FEATURES = 7,
  /**
   * Padding dimension
   */
  HAL_DIM_NAME_PADDING = 8,
  /**
   * Box coordinate dimension (typically 4)
   */
  HAL_DIM_NAME_BOX_COORDS = 9,
} HalDimName;

/**
 * NMS (Non-Maximum Suppression) mode.
 *
 * Controls how overlapping detection boxes are suppressed after decoding.
 *
 * | Mode | Value | Behavior |
 * |------|-------|----------|
 * | HAL_NMS_CLASS_AGNOSTIC | 0 | Suppress overlapping boxes regardless of class |
 * | HAL_NMS_CLASS_AWARE | 1 | Only suppress boxes with the same class label |
 * | HAL_NMS_NONE | 2 | Disable NMS (for end-to-end models with embedded NMS) |
 *
 * Most YOLO models use HAL_NMS_CLASS_AGNOSTIC. Use HAL_NMS_NONE for
 * end-to-end models (e.g. `decoder_version: yolo26` in EdgeFirst metadata)
 * that perform NMS internally.
 */
typedef enum hal_nms {
  /**
   * Class-agnostic NMS: suppress overlapping boxes regardless of class.
   * This is the most common mode for YOLO detection models.
   */
  HAL_NMS_CLASS_AGNOSTIC = 0,
  /**
   * Class-aware NMS: only suppress boxes with the same class label.
   * Use when different classes may legitimately overlap (e.g. person + car).
   */
  HAL_NMS_CLASS_AWARE = 1,
  /**
   * No NMS: skip post-processing suppression entirely.
   * Use for end-to-end models that include NMS in the model graph.
   */
  HAL_NMS_NONE = 2,
} hal_nms;

/**
 * Decoder version for Ultralytics models.
 *
 * Determines the YOLO architecture version and decoding strategy.
 *
 * @see hal_decoder_params_set_decoder_version
 */
typedef enum HalDecoderVersion {
  /**
   * YOLOv5 - anchor-based decoder, requires external NMS
   */
  HAL_DECODER_VERSION_YOLOV5 = 0,
  /**
   * YOLOv8 - anchor-free DFL decoder, requires external NMS
   */
  HAL_DECODER_VERSION_YOLOV8 = 1,
  /**
   * YOLO11 - anchor-free DFL decoder, requires external NMS
   */
  HAL_DECODER_VERSION_YOLO11 = 2,
  /**
   * YOLO26 - end-to-end model with embedded NMS
   */
  HAL_DECODER_VERSION_YOLO26 = 3,
} HalDecoderVersion;

/**
 * Image pixel format (FourCC codes).
 */
typedef enum hal_fourcc {
  /**
   * 8-bit interleaved YUV422, limited range (YUYV)
   */
  HAL_FOURCC_YUYV = 0,
  /**
   * 8-bit planar YUV420, limited range (NV12)
   */
  HAL_FOURCC_NV12 = 1,
  /**
   * 8-bit planar YUV422, limited range (NV16)
   */
  HAL_FOURCC_NV16 = 2,
  /**
   * 8-bit RGBA (4 channels)
   */
  HAL_FOURCC_RGBA = 3,
  /**
   * 8-bit RGB (3 channels)
   */
  HAL_FOURCC_RGB = 4,
  /**
   * 8-bit grayscale, full range (Y800)
   */
  HAL_FOURCC_GREY = 5,
  /**
   * 8-bit planar RGB (3 planes)
   */
  HAL_FOURCC_PLANAR_RGB = 6,
  /**
   * 8-bit planar RGBA (4 planes)
   */
  HAL_FOURCC_PLANAR_RGBA = 7,
  /**
   * 8-bit BGRA (4 channels, blue first)
   */
  HAL_FOURCC_BGRA = 8,
  /**
   * 8-bit interleaved YUV422, limited range (VYUY byte order)
   */
  HAL_FOURCC_VYUY = 9,
} hal_fourcc;

/**
 * Data type of tensor elements.
 *
 * Used to query the type of elements stored in a tensor and interpret
 * the void* data pointer returned by hal_tensor_map_data().
 */
typedef enum hal_dtype {
  /**
   * Unsigned 8-bit integer (uint8_t)
   */
  HAL_DTYPE_U8 = 0,
  /**
   * Signed 8-bit integer (int8_t)
   */
  HAL_DTYPE_I8 = 1,
  /**
   * Unsigned 16-bit integer (uint16_t)
   */
  HAL_DTYPE_U16 = 2,
  /**
   * Signed 16-bit integer (int16_t)
   */
  HAL_DTYPE_I16 = 3,
  /**
   * Unsigned 32-bit integer (uint32_t)
   */
  HAL_DTYPE_U32 = 4,
  /**
   * Signed 32-bit integer (int32_t)
   */
  HAL_DTYPE_I32 = 5,
  /**
   * Unsigned 64-bit integer (uint64_t)
   */
  HAL_DTYPE_U64 = 6,
  /**
   * Signed 64-bit integer (int64_t)
   */
  HAL_DTYPE_I64 = 7,
  /**
   * 16-bit floating point (half)
   */
  HAL_DTYPE_F16 = 8,
  /**
   * 32-bit floating point (float)
   */
  HAL_DTYPE_F32 = 9,
  /**
   * 64-bit floating point (double)
   */
  HAL_DTYPE_F64 = 10,
} hal_dtype;

/**
 * Memory allocation type for tensors.
 *
 * Controls how tensor memory is allocated. DMA is recommended for hardware
 * acceleration, while MEM is the fallback for all platforms.
 */
typedef enum hal_tensor_memory {
  /**
   * Regular system memory allocation (available on all platforms)
   */
  HAL_TENSOR_MEMORY_MEM = 0,
  /**
   * Direct Memory Access allocation (Linux only, enables hardware acceleration)
   */
  HAL_TENSOR_MEMORY_DMA = 1,
  /**
   * POSIX Shared Memory allocation (Linux only, for IPC)
   */
  HAL_TENSOR_MEMORY_SHM = 2,
  /**
   * GPU Pixel Buffer Object allocation (zero-copy GPU upload/readback)
   */
  HAL_TENSOR_MEMORY_PBO = 3,
} hal_tensor_memory;

/**
 * Compute backend selection for image processing.
 *
 * @see hal_image_processor_new_with_backend
 */
typedef enum hal_compute_backend {
  /**
   * Auto-detect based on hardware and environment variables.
   */
  HAL_COMPUTE_BACKEND_AUTO = 0,
  /**
   * CPU-only processing.
   */
  HAL_COMPUTE_BACKEND_CPU = 1,
  /**
   * Prefer G2D hardware blitter (with CPU fallback).
   */
  HAL_COMPUTE_BACKEND_G2D = 2,
  /**
   * Prefer OpenGL ES (with CPU fallback).
   */
  HAL_COMPUTE_BACKEND_OPENGL = 3,
} hal_compute_backend;

/**
 * Image rotation angles.
 */
typedef enum hal_rotation {
  /**
   * No rotation
   */
  HAL_ROTATION_NONE = 0,
  /**
   * 90 degrees clockwise
   */
  HAL_ROTATION_ROTATE90 = 1,
  /**
   * 180 degrees
   */
  HAL_ROTATION_ROTATE180 = 2,
  /**
   * 270 degrees clockwise (90 degrees counter-clockwise)
   */
  HAL_ROTATION_ROTATE270 = 3,
} hal_rotation;

/**
 * Image flip modes.
 */
typedef enum hal_flip {
  /**
   * No flip
   */
  HAL_FLIP_NONE = 0,
  /**
   * Vertical flip (top to bottom)
   */
  HAL_FLIP_VERTICAL = 1,
  /**
   * Horizontal flip (left to right)
   */
  HAL_FLIP_HORIZONTAL = 2,
} hal_flip;

/**
 * Log severity level.
 *
 * Maps 1:1 to Rust `log::Level`.
 */
typedef enum hal_log_level {
  /**
   * Errors — unrecoverable or unexpected failures.
   */
  HAL_LOG_LEVEL_ERROR = 1,
  /**
   * Warnings — degraded but recoverable situations.
   */
  HAL_LOG_LEVEL_WARN = 2,
  /**
   * Informational messages.
   */
  HAL_LOG_LEVEL_INFO = 3,
  /**
   * Debug-level detail.
   */
  HAL_LOG_LEVEL_DEBUG = 4,
  /**
   * Fine-grained trace output.
   */
  HAL_LOG_LEVEL_TRACE = 5,
} hal_log_level;

/**
 * Opaque ByteTrack tracker type.
 */
typedef struct hal_bytetrack hal_bytetrack;

/**
 * Opaque decoder type.
 */
typedef struct hal_decoder hal_decoder;

/**
 * Opaque decoder construction parameters.
 *
 * Configures how ML model outputs are decoded into detection boxes and
 * segmentation masks. Create with `hal_decoder_params_new()`, configure
 * with setter functions, then pass to `hal_decoder_new()`.
 *
 * Configuration can be provided in two ways (mutually exclusive):
 * 1. From a file or string: `hal_decoder_params_set_config_file()`,
 *    `hal_decoder_params_set_config_json()`, or
 *    `hal_decoder_params_set_config_yaml()`
 * 2. Programmatically: `hal_decoder_params_add_output()` to define each
 *    model output tensor
 *
 * @section dp_programmatic Programmatic Configuration
 * @code{.c}
 * hal_decoder_params *params = hal_decoder_params_new();
 *
 * size_t scores_shape[] = {1, 80, 8400};
 * enum hal_dim_name scores_dims[] = {HAL_DIM_BATCH, HAL_DIM_NUM_CLASSES,
 *                                     HAL_DIM_NUM_BOXES};
 * int s = hal_decoder_params_add_output(params, HAL_OUTPUT_SCORES,
 *             HAL_DECODER_ULTRALYTICS, scores_shape, scores_dims, 3);
 * hal_decoder_params_output_set_quantization(params, s, 0.003906f, 0);
 *
 * size_t boxes_shape[] = {1, 4, 8400};
 * enum hal_dim_name boxes_dims[] = {HAL_DIM_BATCH, HAL_DIM_BOX_COORDS,
 *                                    HAL_DIM_NUM_BOXES};
 * int b = hal_decoder_params_add_output(params, HAL_OUTPUT_BOXES,
 *             HAL_DECODER_ULTRALYTICS, boxes_shape, boxes_dims, 3);
 * hal_decoder_params_output_set_quantization(params, b, 0.019824f, 0);
 *
 * hal_decoder_params_set_nms(params, HAL_NMS_CLASS_AGNOSTIC);
 * hal_decoder *decoder = hal_decoder_new(params);
 * hal_decoder_params_free(params);
 * @endcode
 *
 * @section dp_file File-based Configuration
 * @code{.c}
 * hal_decoder_params *params = hal_decoder_params_new();
 * hal_decoder_params_set_config_file(params, "/models/yolov8n/edgefirst.yaml");
 * hal_decoder_params_set_score_threshold(params, 0.25f);
 * hal_decoder *decoder = hal_decoder_new(params);
 * hal_decoder_params_free(params);
 * @endcode
 *
 * @see hal_decoder_params_new, hal_decoder_params_free, hal_decoder_new
 */
typedef struct hal_decoder_params hal_decoder_params;

/**
 * List of detection boxes.
 */
typedef struct hal_detect_box_list hal_detect_box_list;

/**
 * Opaque image processor type.
 *
 * The ImageProcessor handles format conversion with hardware acceleration when available.
 */
typedef struct hal_image_processor hal_image_processor;

/**
 * List of segmentation results.
 */
typedef struct hal_segmentation_list hal_segmentation_list;

/**
 * Type-erased tensor that can hold any supported data type.
 *
 * This is an opaque type - use hal_tensor_* functions to interact with it.
 */
typedef struct hal_tensor hal_tensor;

/**
 * Type-erased tensor map for CPU access to tensor data.
 *
 * This is an opaque type - use hal_tensor_map_* functions to interact with it.
 */
typedef struct hal_tensor_map hal_tensor_map;

/**
 * List of track info results.
 */
typedef struct hal_track_info_list hal_track_info_list;

/**
 * Quantization parameters for dequantizing tensor data.
 */
typedef struct hal_quantization {
  /**
   * Scale factor for dequantization
   */
  float scale;
  /**
   * Zero point for dequantization
   */
  int32_t zero_point;
} hal_quantization;

/**
 * Detection box result.
 */
typedef struct hal_detect_box {
  /**
   * Left-most normalized coordinate (xmin)
   */
  float xmin;
  /**
   * Top-most normalized coordinate (ymin)
   */
  float ymin;
  /**
   * Right-most normalized coordinate (xmax)
   */
  float xmax;
  /**
   * Bottom-most normalized coordinate (ymax)
   */
  float ymax;
  /**
   * Confidence score
   */
  float score;
  /**
   * Class label index
   */
  size_t label;
} hal_detect_box;

/**
 * Rectangle structure for defining regions.
 */
typedef struct hal_rect {
  /**
   * Left edge (x coordinate)
   */
  size_t left;
  /**
   * Top edge (y coordinate)
   */
  size_t top;
  /**
   * Width of the rectangle
   */
  size_t width;
  /**
   * Height of the rectangle
   */
  size_t height;
} hal_rect;

/**
 * Crop configuration for image conversion.
 *
 * Specifies source crop region, destination placement, and background color.
 */
typedef struct hal_crop {
  /**
   * Source rectangle to crop from
   */
  struct hal_rect src_rect;
  /**
   * Destination rectangle to place crop into
   */
  struct hal_rect dst_rect;
  /**
   * Background color (RGBA)
   */
  uint8_t dst_color[4];
  /**
   * Whether src_rect is set
   */
  bool has_src_rect;
  /**
   * Whether dst_rect is set
   */
  bool has_dst_rect;
  /**
   * Whether dst_color is set
   */
  bool has_dst_color;
} hal_crop;

/**
 * Callback function type for log messages.
 *
 * @param level     Severity level of the message
 * @param target    Module path that produced the message (null-terminated)
 * @param message   Log message text (null-terminated)
 * @param userdata  Opaque pointer passed to `hal_log_init_callback`
 */
typedef void (*hal_log_callback)(enum hal_log_level level,
                                 const char *target,
                                 const char *message,
                                 void *userdata);

/**
 * Track information for a tracked object.
 */
typedef struct hal_track_info {
  /**
   * Unique identifier for this track (16 bytes UUID)
   */
  uint8_t uuid[16];
  /**
   * Predicted location in XYXY format (xmin, ymin, xmax, ymax)
   */
  float location[4];
  /**
   * Number of times this track has been updated
   */
  int32_t count;
  /**
   * Timestamp when this track was first created (nanoseconds)
   */
  uint64_t created;
  /**
   * Timestamp of the last update (nanoseconds)
   */
  uint64_t last_updated;
} hal_track_info;

/**
 * Create new decoder parameters.
 *
 * Returns an opaque handle initialized with safe defaults:
 *
 * | Setting | Default |
 * |---------|---------|
 * | score_threshold | 0.5 |
 * | iou_threshold | 0.5 |
 * | nms | HAL_NMS_CLASS_AGNOSTIC |
 *
 * The caller must configure outputs (via `hal_decoder_params_add_output()`,
 * `hal_decoder_params_set_config_file()`, `hal_decoder_params_set_config_json()`,
 * or `hal_decoder_params_set_config_yaml()`) before passing to
 * `hal_decoder_new()`. Free with `hal_decoder_params_free()` after use.
 *
 * @return New params handle, or NULL on allocation failure
 *
 * @par Example
 * @code{.c}
 * hal_decoder_params *params = hal_decoder_params_new();
 * hal_decoder_params_set_config_file(params, "edgefirst.yaml");
 * hal_decoder_params_set_score_threshold(params, 0.3f);
 * hal_decoder *decoder = hal_decoder_new(params);
 * hal_decoder_params_free(params);
 * @endcode
 *
 * @see hal_decoder_params_free, hal_decoder_new
 */
struct hal_decoder_params *hal_decoder_params_new(void);

/**
 * Free decoder parameters.
 *
 * @param params Params handle to free (can be NULL, no-op)
 *
 * @see hal_decoder_params_new
 */
void hal_decoder_params_free(struct hal_decoder_params *params);

/**
 * Set decoder configuration from a JSON string.
 *
 * @param params Params handle
 * @param json   JSON string (null-terminated)
 * @param len    String length in bytes (excluding null terminator),
 *               or 0 to use strlen
 * @return 0 on success, -1 on error (errno = EINVAL)
 *
 * @see hal_decoder_params_set_config_yaml, hal_decoder_params_set_config_file
 */
int hal_decoder_params_set_config_json(struct hal_decoder_params *params,
                                       const char *json,
                                       size_t len);

/**
 * Set decoder configuration from a YAML string.
 *
 * @param params Params handle
 * @param yaml   YAML string (null-terminated)
 * @param len    String length in bytes (excluding null terminator),
 *               or 0 to use strlen
 * @return 0 on success, -1 on error (errno = EINVAL)
 *
 * @see hal_decoder_params_set_config_json, hal_decoder_params_set_config_file
 */
int hal_decoder_params_set_config_yaml(struct hal_decoder_params *params,
                                       const char *yaml,
                                       size_t len);

/**
 * Set decoder configuration from a file path.
 *
 * The file is read when `hal_decoder_new()` is called, not immediately.
 * JSON and YAML are auto-detected from the file extension and content.
 *
 * @param params Params handle
 * @param path   File path (null-terminated)
 * @return 0 on success, -1 on error (errno = EINVAL)
 *
 * @see hal_decoder_params_set_config_json, hal_decoder_params_set_config_yaml
 */
int hal_decoder_params_set_config_file(struct hal_decoder_params *params, const char *path);

/**
 * Add a model output tensor to the decoder configuration.
 *
 * Builds the output configuration programmatically. Each call adds one
 * output tensor description. The decoder resolves the model type
 * automatically from the combination of outputs.
 *
 * @param params  Params handle
 * @param type_   Output tensor role (scores, boxes, detection, etc.)
 * @param decoder Framework that produced the model (ultralytics, modelpack)
 * @param shape   Array of dimension sizes (length = ndim)
 * @param dims    Array of dimension names (length = ndim), or NULL for
 *                unnamed dimensions. When non-NULL, named dimensions
 *                (dshape) are stored and shape is derived from them.
 * @param ndim    Number of dimensions
 * @return Output index (>= 0) on success, -1 on error (errno = EINVAL)
 *
 * @par Example
 * @code{.c}
 * size_t shape[] = {1, 80, 8400};
 * enum hal_dim_name dims[] = {HAL_DIM_BATCH, HAL_DIM_NUM_CLASSES,
 *                              HAL_DIM_NUM_BOXES};
 * int idx = hal_decoder_params_add_output(params, HAL_OUTPUT_SCORES,
 *               HAL_DECODER_ULTRALYTICS, shape, dims, 3);
 * @endcode
 *
 * @see hal_decoder_params_output_set_quantization
 */
int hal_decoder_params_add_output(struct hal_decoder_params *params,
                                  enum HalOutputType type,
                                  enum HalDecoderType decoder,
                                  const size_t *shape,
                                  const enum HalDimName *dims,
                                  size_t ndim);

/**
 * Set quantization parameters on an output by index.
 *
 * @param params     Params handle
 * @param index      Output index (returned by `hal_decoder_params_add_output`)
 * @param scale      Quantization scale
 * @param zero_point Quantization zero point
 * @return 0 on success, -1 on error (errno = EINVAL)
 *
 * @see hal_decoder_params_add_output
 */
int hal_decoder_params_output_set_quantization(struct hal_decoder_params *params,
                                               int index,
                                               float scale,
                                               int zero_point);

/**
 * Set anchor boxes on a detection output by index.
 *
 * Only valid for `HAL_OUTPUT_DETECTION` outputs.
 *
 * @param params      Params handle
 * @param index       Output index (returned by `hal_decoder_params_add_output`)
 * @param anchors     Array of [width, height] anchor pairs
 * @param num_anchors Number of anchor pairs
 * @return 0 on success, -1 on error (errno = EINVAL)
 *
 * @see hal_decoder_params_add_output
 */
int hal_decoder_params_output_set_anchors(struct hal_decoder_params *params,
                                          int index,
                                          const float (*anchors)[2],
                                          size_t num_anchors);

/**
 * Set the normalized flag on a detection or boxes output by index.
 *
 * Only valid for `HAL_OUTPUT_DETECTION` and `HAL_OUTPUT_BOXES` outputs.
 *
 * @param params     Params handle
 * @param index      Output index (returned by `hal_decoder_params_add_output`)
 * @param normalized Non-zero for normalized [0,1] coordinates, 0 for pixel
 * @return 0 on success, -1 on error (errno = EINVAL)
 *
 * @see hal_decoder_params_add_output
 */
int hal_decoder_params_output_set_normalized(struct hal_decoder_params *params,
                                             int index,
                                             int normalized);

/**
 * Set the score threshold.
 *
 * Detections with confidence below this threshold are discarded.
 *
 * @param params Params handle
 * @param threshold Score threshold (default: 0.5)
 * @return 0 on success, -1 on error (errno = EINVAL)
 */
int hal_decoder_params_set_score_threshold(struct hal_decoder_params *params, float threshold);

/**
 * Set the IoU (Intersection over Union) threshold for NMS.
 *
 * @param params Params handle
 * @param threshold IoU threshold (default: 0.5)
 * @return 0 on success, -1 on error (errno = EINVAL)
 */
int hal_decoder_params_set_iou_threshold(struct hal_decoder_params *params, float threshold);

/**
 * Set the NMS (Non-Maximum Suppression) mode.
 *
 * @param params Params handle
 * @param nms NMS mode
 * @return 0 on success, -1 on error (errno = EINVAL)
 *
 * @see HalNms
 */
int hal_decoder_params_set_nms(struct hal_decoder_params *params, enum hal_nms nms);

/**
 * Set the decoder version for Ultralytics models.
 *
 * Determines the YOLO architecture version and decoding strategy.
 *
 * @param params  Params handle
 * @param version Decoder version
 * @return 0 on success, -1 on error (errno = EINVAL)
 *
 * @see HalDecoderVersion
 */
int hal_decoder_params_set_decoder_version(struct hal_decoder_params *params,
                                           enum HalDecoderVersion version);

/**
 * Create a new decoder from parameters.
 *
 * Validates the parameters and constructs a decoder ready for use with
 * `hal_decoder_decode()`. Configuration must be provided either via
 * `hal_decoder_params_add_output()` (programmatic) or via one of the
 * config file/string setters (mutually exclusive).
 *
 * @param params Params handle (must not be NULL)
 * @return New decoder handle on success, NULL on error (errno set)
 *
 * @par Errors (errno):
 * - EINVAL: NULL params or no configuration provided
 * - ENOENT: Config file path does not exist
 * - EIO: Config file could not be read
 * - EBADMSG: Configuration is syntactically valid but semantically invalid
 *   (e.g. missing required `outputs` array, unknown decoder type)
 *
 * @par Example
 * @code{.c}
 * hal_decoder_params *params = hal_decoder_params_new();
 * hal_decoder_params_set_config_file(params, "/models/yolov8n/edgefirst.yaml");
 * hal_decoder_params_set_score_threshold(params, 0.25f);
 * hal_decoder_params_set_iou_threshold(params, 0.45f);
 * hal_decoder_params_set_nms(params, HAL_NMS_CLASS_AWARE);
 *
 * hal_decoder *decoder = hal_decoder_new(params);
 * if (!decoder) {
 *     fprintf(stderr, "decoder: %s\n", strerror(errno));
 *     hal_decoder_params_free(params);
 *     return -1;
 * }
 *
 * // ... use decoder with hal_decoder_decode() ...
 *
 * hal_decoder_params_free(params);
 * hal_decoder_free(decoder);
 * @endcode
 *
 * @see hal_decoder_params_new, hal_decoder_params_free, hal_decoder_free
 */
struct hal_decoder *hal_decoder_new(const struct hal_decoder_params *params);

/**
 * Decode model outputs into detection boxes and segmentation masks.
 *
 * Automatically selects the decoding path based on tensor dtype:
 * - f32 tensors → `decode_float` path
 * - Integer tensors (u8, i8, u16, i16, u32, i32) → `decode_quantized` path
 *
 * All output tensors must be the same general category (all float or all integer).
 *
 * @param decoder Decoder handle
 * @param outputs Array of output tensor pointers
 * @param num_outputs Number of output tensors
 * @param out_boxes Output parameter for detection box list (caller must free)
 * @param out_segmentations Output parameter for segmentation list (can be NULL; caller must free if non-NULL)
 * @return 0 on success, -1 on error
 * @par Errors (errno):
 * - EINVAL: Invalid argument (NULL decoder/outputs/out_boxes, mixed dtypes)
 * - EIO: Decoding failed
 */
int hal_decoder_decode(const struct hal_decoder *decoder,
                       const struct hal_tensor *const *outputs,
                       size_t num_outputs,
                       struct hal_detect_box_list **out_boxes,
                       struct hal_segmentation_list **out_segmentations);

/**
 * Get the model type string from a decoder.
 *
 * Returns a human-readable string identifying the model type (e.g., "yolo_det",
 * "modelpack_segdet"). The returned string is owned by the caller and must be
 * freed with free().
 *
 * @param decoder Decoder handle
 * @return Newly allocated C string with model type, or NULL on error
 * @par Errors (errno):
 * - EINVAL: NULL decoder
 */
char *hal_decoder_model_type(const struct hal_decoder *decoder);

/**
 * Get whether the decoder produces normalized box coordinates.
 *
 * @param decoder Decoder handle
 * @return 1 if boxes are in normalized [0,1] coordinates,
 *         0 if boxes are in pixel coordinates,
 *        -1 if unknown or decoder is NULL
 */
int hal_decoder_normalized_boxes(const struct hal_decoder *decoder);

/**
 * Dequantize an integer tensor into a float tensor.
 *
 * Converts quantized integer data to float using: output = (input - zero_point) * scale.
 * The input tensor must be an integer dtype (u8, i8, u16, i16, u32, i32).
 * The output tensor must be f32 dtype and have the same total number of elements.
 *
 * @param input Input integer tensor (not consumed)
 * @param quant Quantization parameters (scale and zero_point)
 * @param output Output f32 tensor (must be pre-allocated with same element count)
 * @return 0 on success, -1 on error
 * @par Errors (errno):
 * - EINVAL: NULL input/output, input is not integer, output is not f32, size mismatch
 * - EIO: Failed to map tensors
 */
int hal_dequantize(const struct hal_tensor *input,
                   struct hal_quantization quant,
                   struct hal_tensor *output);

/**
 * Convert a 3D segmentation mask into a 2D binary mask tensor.
 *
 * Takes a segmentation from a segmentation list by index and converts it
 * to a 2D binary mask (height x width) as a new u8 tensor.
 * If the segmentation has depth=1, values >= 128 become 1, < 128 become 0.
 * If depth > 1, argmax across the depth dimension is used.
 *
 * @param list Segmentation list handle
 * @param index Index of the segmentation (0-based)
 * @return New u8 tensor with shape [height, width], or NULL on error
 * @par Errors (errno):
 * - EINVAL: NULL list, index out of bounds, or invalid segmentation shape
 * - ENOMEM: Memory allocation failed
 */
struct hal_tensor *hal_segmentation_to_mask(const struct hal_segmentation_list *list, size_t index);

/**
 * Free a decoder.
 *
 * @param decoder Decoder handle to free (can be NULL, no-op)
 */
void hal_decoder_free(struct hal_decoder *decoder);

/**
 * Get the number of detections in a list.
 *
 * @param list Detection box list handle
 * @return Number of detections, or 0 if list is NULL
 */
size_t hal_detect_box_list_len(const struct hal_detect_box_list *list);

/**
 * Get a detection box from a list by index.
 *
 * @param list Detection box list handle
 * @param index Index of the detection (0-based)
 * @param out_box Output parameter for the detection box
 * @return 0 on success, -1 on error
 * @par Errors (errno):
 * - EINVAL: Invalid argument (NULL list/out_box, index out of bounds)
 */
int hal_detect_box_list_get(const struct hal_detect_box_list *list,
                            size_t index,
                            struct hal_detect_box *out_box);

/**
 * Free a detection box list.
 *
 * @param list Detection box list handle to free (can be NULL, no-op)
 */
void hal_detect_box_list_free(struct hal_detect_box_list *list);

/**
 * Get the number of segmentations in a list.
 *
 * @param list Segmentation list handle
 * @return Number of segmentations, or 0 if list is NULL
 */
size_t hal_segmentation_list_len(const struct hal_segmentation_list *list);

/**
 * Get the bounding box of a segmentation by index.
 *
 * @param list Segmentation list handle
 * @param index Index of the segmentation (0-based)
 * @param xmin Output parameter for left coordinate
 * @param ymin Output parameter for top coordinate
 * @param xmax Output parameter for right coordinate
 * @param ymax Output parameter for bottom coordinate
 * @return 0 on success, -1 on error
 * @par Errors (errno):
 * - EINVAL: Invalid argument (NULL list/outputs, index out of bounds)
 */
int hal_segmentation_list_get_bbox(const struct hal_segmentation_list *list,
                                   size_t index,
                                   float *xmin,
                                   float *ymin,
                                   float *xmax,
                                   float *ymax);

/**
 * Get the mask data of a segmentation by index.
 *
 * The returned pointer is borrowed and valid only during the list's lifetime.
 *
 * @param list Segmentation list handle
 * @param index Index of the segmentation (0-based)
 * @param out_height Output parameter for mask height
 * @param out_width Output parameter for mask width
 * @return Pointer to mask data (uint8_t array), or NULL on error
 * @par Errors (errno):
 * - EINVAL: Invalid argument (NULL list, index out of bounds)
 */
const uint8_t *hal_segmentation_list_get_mask(const struct hal_segmentation_list *list,
                                              size_t index,
                                              size_t *out_height,
                                              size_t *out_width);

/**
 * Free a segmentation list.
 *
 * @param list Segmentation list handle to free (can be NULL, no-op)
 */
void hal_segmentation_list_free(struct hal_segmentation_list *list);

/**
 * Decode model outputs and draw masks directly onto a destination image.
 *
 * This is the fused path: for segmentation models, prototype data is passed
 * directly to the renderer without materializing intermediate mask arrays.
 * For detection-only models, this falls back to decode + draw_masks.
 *
 * @param decoder Decoder handle
 * @param processor Image processor handle
 * @param outputs Array of output tensor pointers
 * @param num_outputs Number of output tensors
 * @param dst Destination image to draw onto
 * @param out_boxes Output parameter for detection box list (caller must free)
 * @return 0 on success, -1 on error
 * @par Errors (errno):
 * - EINVAL: Invalid argument (NULL decoder/processor/outputs/dst/out_boxes)
 * - EIO: Decoding or drawing failed
 */
int hal_decoder_draw_masks(const struct hal_decoder *decoder,
                           struct hal_image_processor *processor,
                           const struct hal_tensor *const *outputs,
                           size_t num_outputs,
                           struct hal_tensor *dst,
                           struct hal_detect_box_list **out_boxes);

/**
 * Decode model outputs and return masks at a specified output resolution.
 *
 * Internally renders masks into a compact atlas and splits them into
 * individual per-detection segmentation results. The returned
 * `out_masks` is a segmentation list where each entry contains a
 * binary mask cropped to the detection's bounding box.
 *
 * @param decoder Decoder handle
 * @param processor Image processor handle
 * @param outputs Array of output tensor pointers
 * @param num_outputs Number of output tensors
 * @param output_width Target mask width
 * @param output_height Target mask height
 * @param out_boxes Output parameter for detection box list (caller must free)
 * @param out_masks Output parameter for segmentation list (caller must free)
 * @return 0 on success, -1 on error
 * @par Errors (errno):
 * - EINVAL: Invalid argument (NULL decoder/processor/outputs/out_boxes/out_masks)
 * - EIO: Decoding failed
 */
int hal_decoder_decode_masks(const struct hal_decoder *decoder,
                             struct hal_image_processor *processor,
                             const struct hal_tensor *const *outputs,
                             size_t num_outputs,
                             size_t output_width,
                             size_t output_height,
                             struct hal_detect_box_list **out_boxes,
                             struct hal_segmentation_list **out_masks);

/**
 * Create a new rectangle.
 *
 * @param left Left edge (x coordinate)
 * @param top Top edge (y coordinate)
 * @param width Width of the rectangle
 * @param height Height of the rectangle
 * @return New rectangle structure
 */
struct hal_rect hal_rect_new(size_t left, size_t top, size_t width, size_t height);

/**
 * Create a new default crop configuration.
 *
 * @return New crop structure with all fields unset
 */
struct hal_crop hal_crop_new(void);

/**
 * Set the source rectangle for a crop configuration.
 *
 * @param crop Crop configuration to modify
 * @param rect Source rectangle (can be NULL to clear)
 */
void hal_crop_set_src_rect(struct hal_crop *crop, const struct hal_rect *rect);

/**
 * Set the destination rectangle for a crop configuration.
 *
 * @param crop Crop configuration to modify
 * @param rect Destination rectangle (can be NULL to clear)
 */
void hal_crop_set_dst_rect(struct hal_crop *crop, const struct hal_rect *rect);

/**
 * Set the background color for a crop configuration.
 *
 * @param crop Crop configuration to modify
 * @param r Red component (0-255)
 * @param g Green component (0-255)
 * @param b Blue component (0-255)
 * @param a Alpha component (0-255)
 */
void hal_crop_set_dst_color(struct hal_crop *crop, uint8_t r, uint8_t g, uint8_t b, uint8_t a);

/**
 * Create a new empty image tensor.
 *
 * @note When an image processor is available, prefer
 * hal_image_processor_create_image() which selects the optimal memory
 * backend (DMA-buf, PBO, or system memory) automatically. Direct
 * allocation via this function bypasses PBO-backed GPU zero-copy paths.
 *
 * @param width Image width in pixels
 * @param height Image height in pixels
 * @param fourcc Pixel format (HAL_FOURCC_*)
 * @param dtype Data type of tensor elements (HAL_DTYPE_*)
 * @param memory Memory allocation type (HAL_TENSOR_DMA recommended)
 * @return New tensor handle on success, NULL on error
 * @par Errors (errno):
 * - EINVAL: Invalid argument (zero dimensions, unsupported format)
 * - ENOMEM: Memory allocation failed
 */
struct hal_tensor *hal_tensor_new_image(size_t width,
                                        size_t height,
                                        enum hal_fourcc fourcc,
                                        enum hal_dtype dtype,
                                        enum hal_tensor_memory memory);

/**
 * Load an image from memory (JPEG or PNG).
 *
 * Automatically detects format and decodes the image.
 *
 * @param data Pointer to image data
 * @param len Length of image data in bytes
 * @param fourcc Output pixel format (HAL_FOURCC_RGB, HAL_FOURCC_RGBA, or HAL_FOURCC_GREY)
 * @param memory Memory allocation type
 * @return New tensor handle on success, NULL on error
 * @par Errors (errno):
 * - EINVAL: Invalid argument (NULL data, zero length)
 * - EBADMSG: Failed to decode image
 * - ENOMEM: Memory allocation failed
 */
struct hal_tensor *hal_tensor_load_image(const uint8_t *data,
                                         size_t len,
                                         enum hal_fourcc fourcc,
                                         enum hal_tensor_memory memory);

/**
 * Load an image from a file (JPEG or PNG).
 *
 * @param path Path to the image file
 * @param fourcc Output pixel format
 * @param memory Memory allocation type
 * @return New tensor handle on success, NULL on error
 * @par Errors (errno):
 * - EINVAL: Invalid argument (NULL path)
 * - ENOENT: File not found
 * - EBADMSG: Failed to decode image
 * - ENOMEM: Memory allocation failed
 */
struct hal_tensor *hal_tensor_load_image_file(const char *path,
                                              enum hal_fourcc fourcc,
                                              enum hal_tensor_memory memory);

/**
 * Create a multiplane image tensor from separate Y and UV DMA-BUF file descriptors.
 *
 * This is used for V4L2 multi-planar NV12 (`V4L2_PIX_FMT_NV12M`) where the
 * Y and UV planes are in separate DMA-BUF allocations.
 *
 * **Ownership**: Ownership is transferred once the function validates that
 * both FDs are non-negative, non-zero dimensions, and distinct. After that
 * point, the HAL closes them on any error. If validation of the FD values
 * themselves fails (negative FD, zero dimensions, or `y_fd == uv_fd`), the
 * caller retains ownership.
 *
 * @param y_fd    DMA-BUF file descriptor for the Y (luma) plane
 * @param width   Image width in pixels
 * @param height  Image height in pixels
 * @param uv_fd   DMA-BUF file descriptor for the UV (chroma) plane
 * @param fourcc  Pixel format (must be HAL_FOURCC_NV12 or HAL_FOURCC_NV16)
 * @param out     Receives the new tensor handle on success
 * @return 0 on success, -1 on error (errno set)
 * @par Errors (errno):
 * - EINVAL: Invalid argument or unsupported fourcc
 * - EIO:    Failed to wrap DMA-BUF file descriptor
 */
int hal_tensor_from_planes(int y_fd,
                           uint32_t width,
                           uint32_t height,
                           int uv_fd,
                           enum hal_fourcc fourcc,
                           struct hal_tensor **out);

/**
 * Load a JPEG image from memory.
 *
 * @param data Pointer to JPEG data
 * @param len Length of JPEG data in bytes
 * @param fourcc Output pixel format (HAL_FOURCC_RGB, HAL_FOURCC_RGBA, or HAL_FOURCC_GREY)
 * @param memory Memory allocation type
 * @return New tensor handle on success, NULL on error
 * @par Errors (errno):
 * - EINVAL: Invalid argument (NULL data, zero length)
 * - EBADMSG: Failed to decode JPEG
 * - ENOMEM: Memory allocation failed
 */
struct hal_tensor *hal_tensor_load_jpeg(const uint8_t *data,
                                        size_t len,
                                        enum hal_fourcc fourcc,
                                        enum hal_tensor_memory memory);

/**
 * Load a PNG image from memory.
 *
 * @param data Pointer to PNG data
 * @param len Length of PNG data in bytes
 * @param fourcc Output pixel format (HAL_FOURCC_RGB, HAL_FOURCC_RGBA, or HAL_FOURCC_GREY)
 * @param memory Memory allocation type
 * @return New tensor handle on success, NULL on error
 * @par Errors (errno):
 * - EINVAL: Invalid argument (NULL data, zero length)
 * - EBADMSG: Failed to decode PNG
 * - ENOMEM: Memory allocation failed
 */
struct hal_tensor *hal_tensor_load_png(const uint8_t *data,
                                       size_t len,
                                       enum hal_fourcc fourcc,
                                       enum hal_tensor_memory memory);

/**
 * Save an image tensor as JPEG.
 *
 * @param tensor Image tensor to save
 * @param path Output file path
 * @param quality JPEG quality (1-100, 0 for default)
 * @return 0 on success, -1 on error
 * @par Errors (errno):
 * - EINVAL: Invalid argument (NULL tensor/path)
 * - EIO: Failed to write file
 */
int hal_tensor_save_jpeg(const struct hal_tensor *tensor, const char *path, int quality);

/**
 * Get the width of an image tensor.
 *
 * @param tensor Image tensor handle
 * @return Width in pixels, or 0 if tensor is NULL or not an image
 */
size_t hal_tensor_width(const struct hal_tensor *tensor);

/**
 * Get the height of an image tensor.
 *
 * @param tensor Image tensor handle
 * @return Height in pixels, or 0 if tensor is NULL or not an image
 */
size_t hal_tensor_height(const struct hal_tensor *tensor);

/**
 * Get the pixel format of an image tensor.
 *
 * @param tensor Image tensor handle
 * @return Pixel format, or HAL_FOURCC_RGB if tensor is NULL or not an image
 */
enum hal_fourcc hal_tensor_fourcc(const struct hal_tensor *tensor);

/**
 * Attach pixel format metadata to a tensor.
 *
 * Validates that the tensor's shape is compatible with the format's
 * layout (packed, planar, or semi-planar). This enables tensors
 * created via `hal_tensor_from_fd()` to be used as image conversion
 * destinations.
 *
 * @param tensor Tensor handle
 * @param fourcc Pixel format to attach (HAL_FOURCC_*)
 * @return 0 on success, -1 on error
 * @par Errors (errno):
 * - EINVAL: NULL tensor or shape doesn't match format layout
 */
int hal_tensor_set_format(struct hal_tensor *tensor, enum hal_fourcc fourcc);

/**
 * Check if an image tensor uses a planar pixel format.
 *
 * Planar formats store each color channel in a separate plane (e.g., NV12,
 * NV16, PLANAR_RGB, PLANAR_RGBA), while interleaved formats store channels
 * together per pixel (e.g., RGB, RGBA, YUYV).
 *
 * @param tensor Image tensor handle
 * @return true if the tensor uses a planar format, false if interleaved or NULL
 */
bool hal_tensor_is_planar(const struct hal_tensor *tensor);

/**
 * Get the number of channels in an image tensor.
 *
 * Returns the number of color channels (e.g., 3 for RGB, 4 for RGBA,
 * 1 for GREY/NV12/NV16 (luma plane)).
 *
 * @param tensor Image tensor handle
 * @return Number of channels, or 0 if tensor is NULL or not an image
 */
size_t hal_tensor_channels(const struct hal_tensor *tensor);

/**
 * Get the row stride of an image tensor in bytes.
 *
 * For planar formats this is equal to the width. For interleaved formats
 * this is width * channels.
 *
 * @param tensor Image tensor handle
 * @return Row stride in bytes, or 0 if tensor is NULL or not an image
 */
size_t hal_tensor_row_stride(const struct hal_tensor *tensor);

/**
 * Create a new image processor.
 *
 * Automatically selects the best available backend (G2D, OpenGL, or CPU).
 *
 * @return New image processor handle on success, NULL on error
 * @par Errors (errno):
 * - ENOMEM: Memory allocation failed
 * - ENOTSUP: No suitable image processing backend available
 */
struct hal_image_processor *hal_image_processor_new(void);

/**
 * Create a new image processor with a specific compute backend.
 *
 * When `backend` is not `HAL_COMPUTE_BACKEND_AUTO`, the processor
 * initializes the requested backend plus CPU as a fallback chain.
 * Environment variables (`EDGEFIRST_FORCE_BACKEND`, `EDGEFIRST_DISABLE_*`)
 * are ignored in this case.
 *
 * @param backend Preferred compute backend
 * @return New image processor handle on success, NULL on error
 * @par Errors (errno):
 * - ENOMEM: Memory allocation failed
 * - ENOTSUP: No suitable image processing backend available
 */
struct hal_image_processor *hal_image_processor_new_with_backend(enum hal_compute_backend backend);

/**
 * Convert an image to a different format/size.
 *
 * Performs format conversion, scaling, rotation, flip, and crop operations.
 *
 * @param processor Image processor handle
 * @param src Source image tensor
 * @param dst Destination image tensor (must be pre-allocated with desired dimensions)
 * @param rotation Rotation to apply
 * @param flip Flip to apply
 * @param crop Crop configuration (can be NULL for no crop)
 * @return 0 on success, -1 on error
 * @par Errors (errno):
 * - EINVAL: Invalid argument (NULL processor/src/dst)
 * - EIO: Conversion failed
 */
int hal_image_processor_convert(struct hal_image_processor *processor,
                                const struct hal_tensor *src,
                                struct hal_tensor *dst,
                                enum hal_rotation rotation,
                                enum hal_flip flip,
                                const struct hal_crop *crop);

/**
 * Draw detection boxes and segmentation masks onto an image.
 *
 * Draws bounding boxes (with labels) and segmentation overlays on the
 * destination image tensor. Uses hardware acceleration (OpenGL) when available,
 * falling back to CPU rendering.
 *
 * @param processor Image processor handle
 * @param dst Destination image tensor to draw onto
 * @param detections Detection box list (can be NULL for segmentation-only)
 * @param segmentations Segmentation list (can be NULL for detection-only)
 * @return 0 on success, -1 on error
 * @par Errors (errno):
 * - EINVAL: Invalid argument (NULL processor or dst)
 * - EIO: Drawing failed
 */
int hal_image_processor_draw_masks(struct hal_image_processor *processor,
                                   struct hal_tensor *dst,
                                   const struct hal_detect_box_list *detections,
                                   const struct hal_segmentation_list *segmentations);

/**
 * Set class colors for segmentation rendering.
 *
 * Colors are used when drawing segmentation masks via
 * hal_image_processor_draw_masks(). Each color is an RGBA tuple.
 *
 * @param processor Image processor handle
 * @param colors Pointer to array of RGBA color tuples ([u8; 4] per color)
 * @param num_colors Number of colors in the array
 * @return 0 on success, -1 on error
 * @par Errors (errno):
 * - EINVAL: Invalid argument (NULL processor or colors)
 * - EIO: Failed to set colors
 */
int hal_image_processor_set_class_colors(struct hal_image_processor *processor,
                                         const uint8_t (*colors)[4],
                                         size_t num_colors);

/**
 * Create a new image tensor using the processor's optimal memory backend.
 *
 * Selects the best available backing storage based on hardware capabilities:
 * DMA-buf > PBO (GPU buffer) > system memory. Images created this way benefit
 * from zero-copy GPU paths when used with the same processor's convert().
 *
 * @param processor Image processor handle
 * @param width Image width in pixels
 * @param height Image height in pixels
 * @param fourcc Pixel format (HAL_FOURCC_*)
 * @param dtype Data type of tensor elements (HAL_DTYPE_*)
 * @return New tensor handle on success, NULL on error
 * @par Errors (errno):
 * - EINVAL: Invalid argument (NULL processor, zero dimensions, invalid shape)
 * - ENOTSUP: Unsupported format or operation
 * - EIO: I/O error during DMA or GPU buffer allocation
 * - ENOMEM: Memory allocation failed
 */
struct hal_tensor *hal_image_processor_create_image(struct hal_image_processor *processor,
                                                    size_t width,
                                                    size_t height,
                                                    enum hal_fourcc fourcc,
                                                    enum hal_dtype dtype);

/**
 * Create an image tensor backed by an external DMA-BUF file descriptor.
 *
 * The GPU renders directly into this buffer via EGL DMA-BUF import —
 * no CPU copy is needed after hal_image_processor_convert(). The caller
 * retains ownership of the underlying buffer; the returned tensor borrows
 * it via dup(fd).
 *
 * @param processor Image processor handle
 * @param fd DMA-BUF file descriptor (caller retains ownership)
 * @param width Image width in pixels
 * @param height Image height in pixels
 * @param fourcc Pixel format (HAL_FOURCC_*)
 * @param dtype Data type of tensor elements (HAL_DTYPE_*)
 * @return New tensor handle on success, NULL on error
 * @par Errors (errno):
 * - EINVAL: Invalid argument (NULL processor, zero dimensions, bad fd,
 *   invalid image shape, or not an image)
 * - ENOTSUP: Not supported on this platform
 * - EIO: Underlying I/O error or unexpected internal failure
 */
struct hal_tensor *hal_image_processor_create_image_from_fd(struct hal_image_processor *processor,
                                                            int fd,
                                                            size_t width,
                                                            size_t height,
                                                            enum hal_fourcc fourcc,
                                                            enum hal_dtype dtype);

/**
 * Create image from fd stub for non-Linux platforms.
 */
struct hal_tensor *hal_image_processor_create_image_from_fd(struct hal_image_processor *processor,
                                                            int fd,
                                                            size_t width,
                                                            size_t height,
                                                            enum hal_fourcc fourcc,
                                                            enum hal_dtype dtype);

/**
 * Free an image processor.
 *
 * @param processor Image processor handle to free (can be NULL, no-op)
 */
void hal_image_processor_free(struct hal_image_processor *processor);

/**
 * Initialise HAL logging to a `FILE*` stream.
 *
 * Writes `[LEVEL] target: message` lines to the given stream, typically
 * `stderr`. Only the first successful call takes effect; subsequent calls
 * return `-1` with `errno = EALREADY`.
 *
 * **Thread safety**: The `stream` must remain valid for the lifetime of the
 * process. On glibc/musl, `stderr` and other standard streams are internally
 * locked per-call, so individual lines will not be corrupted. However, two
 * log lines from different threads may interleave. If fully ordered output
 * is required, use `hal_log_init_callback` with an application-side lock.
 *
 * @param stream     Open `FILE*` to write log output to (e.g. `stderr`)
 * @param max_level  Maximum log level to emit (messages above this are dropped)
 * @return 0 on success, -1 on error
 * @par Errors (errno):
 * - EINVAL:  `stream` is NULL
 * - EALREADY: logging has already been initialised
 *
 * @par Example
 * @code{.c}
 * hal_log_init_file(stderr, HAL_LOG_LEVEL_DEBUG);
 * @endcode
 */
int hal_log_init_file(FILE *stream, enum hal_log_level max_level);

/**
 * Initialise HAL logging with a user-provided callback.
 *
 * Each log record is forwarded to `cb` with the level, target module name,
 * formatted message, and the opaque `userdata` pointer. This allows routing
 * HAL log output into GStreamer, syslog, or any other logging framework.
 *
 * Only the first successful call takes effect; subsequent calls return `-1`
 * with `errno = EALREADY`.
 *
 * @param cb         Callback function invoked for each log message
 * @param userdata   Opaque pointer forwarded to the callback (may be NULL)
 * @param max_level  Maximum log level to emit
 * @return 0 on success, -1 on error
 * @par Errors (errno):
 * - EINVAL:  `cb` is NULL
 * - EALREADY: logging has already been initialised
 *
 * @par Example
 * @code{.c}
 * void my_logger(hal_log_level level, const char* target,
 *                const char* message, void* userdata) {
 *     fprintf(stderr, "[%d] %s: %s\n", level, target, message);
 * }
 * hal_log_init_callback(my_logger, NULL, HAL_LOG_LEVEL_TRACE);
 * @endcode
 */
int hal_log_init_callback(hal_log_callback cb, void *userdata, enum hal_log_level max_level);

/**
 * Check if DMA (Direct Memory Access) buffer allocation is available.
 *
 * DMA buffers enable zero-copy data sharing between CPU and hardware
 * accelerators. This is only available on Linux systems with DMA-BUF heap
 * support.
 *
 * @return true if DMA allocation is available, false otherwise
 */
bool hal_is_dma_available(void);

/**
 * Check if POSIX shared memory allocation is available.
 *
 * Shared memory enables zero-copy IPC between processes. This is available
 * on Unix systems (Linux, macOS, BSD).
 *
 * @return true if shared memory allocation is available, false otherwise
 */
bool hal_is_shm_available(void);

/**
 * Create a new tensor with the given data type, shape, and memory type.
 *
 * @param dtype Data type of tensor elements (HAL_DTYPE_*)
 * @param shape Array of dimension sizes (ndim elements)
 * @param ndim Number of dimensions (1-8)
 * @param memory Memory allocation type (HAL_TENSOR_DMA recommended)
 * @param name Optional tensor name for debugging (can be NULL)
 * @return New tensor handle on success, NULL on error
 * @par Errors (errno):
 * - EINVAL: Invalid argument (NULL shape, ndim is 0, invalid dtype)
 * - ENOMEM: Memory allocation failed
 * - EIO: DMA heap not available (falls back to SHM/MEM)
 */
struct hal_tensor *hal_tensor_new(enum hal_dtype dtype,
                                  const size_t *shape,
                                  size_t ndim,
                                  enum hal_tensor_memory memory,
                                  const char *name);

/**
 * Create a new tensor from an existing file descriptor (Linux only).
 *
 * Takes ownership of the file descriptor - caller must NOT close it.
 *
 * @param dtype Data type of tensor elements (HAL_DTYPE_*)
 * @param fd File descriptor for DMA/SHM buffer (ownership transferred)
 * @param shape Array of dimension sizes (ndim elements)
 * @param ndim Number of dimensions (1-8)
 * @param name Optional tensor name for debugging (can be NULL)
 * @return New tensor handle on success, NULL on error
 * @par Errors (errno):
 * - EINVAL: Invalid argument (NULL shape, ndim is 0, invalid fd)
 * - ENOMEM: Memory allocation failed
 * - ENOTSUP: Not supported on this platform (non-Unix)
 */
struct hal_tensor *hal_tensor_from_fd(enum hal_dtype dtype,
                                      int fd,
                                      const size_t *shape,
                                      size_t ndim,
                                      const char *name);

/**
 * Create a new tensor from an existing file descriptor (stub for non-Unix).
 */
struct hal_tensor *hal_tensor_from_fd(enum hal_dtype dtype,
                                      int fd,
                                      const size_t *shape,
                                      size_t ndim,
                                      const char *name);

/**
 * Free a tensor and release its resources.
 *
 * After calling this function, the tensor pointer becomes invalid.
 *
 * @param tensor Tensor handle to free (can be NULL, no-op)
 */
void hal_tensor_free(struct hal_tensor *tensor);

/**
 * Get the data type of a tensor.
 *
 * @param tensor Tensor handle
 * @return Data type enum value, or HAL_DTYPE_U8 if tensor is NULL
 */
enum hal_dtype hal_tensor_dtype(const struct hal_tensor *tensor);

/**
 * Get the size in bytes of the tensor's data type.
 *
 * @param tensor Tensor handle
 * @return Size of one element in bytes, or 0 if tensor is NULL
 */
size_t hal_tensor_dtype_size(const struct hal_tensor *tensor);

/**
 * Get the memory allocation type of a tensor.
 *
 * @param tensor Tensor handle
 * @return Memory type enum value, or HAL_TENSOR_MEM if tensor is NULL
 */
enum hal_tensor_memory hal_tensor_memory_type(const struct hal_tensor *tensor);

/**
 * Get the name of a tensor.
 *
 * The returned string is owned by the caller and must be freed with free().
 *
 * @param tensor Tensor handle
 * @return Newly allocated C string with tensor name, or NULL on error
 */
char *hal_tensor_name(const struct hal_tensor *tensor);

/**
 * Get the shape of a tensor.
 *
 * The returned pointer is borrowed and valid only during the tensor's lifetime.
 *
 * @param tensor Tensor handle
 * @param out_ndim Output parameter for number of dimensions (can be NULL)
 * @return Pointer to shape array, or NULL if tensor is NULL
 */
const size_t *hal_tensor_shape(const struct hal_tensor *tensor, size_t *out_ndim);

/**
 * Get the total number of elements in a tensor.
 *
 * @param tensor Tensor handle
 * @return Number of elements (product of all dimensions), or 0 if tensor is NULL
 */
size_t hal_tensor_len(const struct hal_tensor *tensor);

/**
 * Get the total size in bytes of a tensor's data.
 *
 * @param tensor Tensor handle
 * @return Size in bytes (len * dtype_size), or 0 if tensor is NULL
 */
size_t hal_tensor_size(const struct hal_tensor *tensor);

/**
 * Clone the file descriptor associated with a tensor (Linux only).
 *
 * Creates a new owned file descriptor that the caller must close().
 *
 * @param tensor Tensor handle
 * @return New file descriptor on success, -1 on error
 * @par Errors (errno):
 * - EINVAL: NULL tensor
 * - ENOTSUP: Tensor memory type doesn't support file descriptors, or non-Unix
 * - EIO: Failed to clone file descriptor
 */
int hal_tensor_clone_fd(const struct hal_tensor *tensor);

/**
 * Clone file descriptor stub for non-Unix platforms.
 */
int hal_tensor_clone_fd(const struct hal_tensor *tensor);

/**
 * Clone the DMA-BUF file descriptor backing a tensor.
 *
 * Unlike hal_tensor_clone_fd(), this function returns a clear error if the
 * tensor is not DMA-backed, rather than a generic I/O error. Use this when
 * you specifically need a DMA-BUF fd for zero-copy hardware import.
 *
 * Creates a new owned file descriptor that the caller must close().
 *
 * @param tensor Tensor handle
 * @return New file descriptor on success, -1 on error
 * @par Errors (errno):
 * - EINVAL: NULL tensor
 * - ENOTSUP: Tensor is not DMA-backed (Mem, Shm, or Pbo)
 * - EIO: Failed to clone file descriptor
 */
int hal_tensor_dmabuf_clone(const struct hal_tensor *tensor);

/**
 * Clone DMA-BUF fd stub for non-Linux platforms.
 */
int hal_tensor_dmabuf_clone(const struct hal_tensor *tensor);

/**
 * Reshape a tensor to a new shape.
 *
 * The total number of elements must remain the same.
 *
 * @param tensor Tensor handle
 * @param shape New shape array
 * @param ndim Number of dimensions in new shape
 * @return 0 on success, -1 on error
 * @par Errors (errno):
 * - EINVAL: NULL tensor/shape, ndim is 0, or element count mismatch
 */
int hal_tensor_reshape(struct hal_tensor *tensor, const size_t *shape, size_t ndim);

/**
 * Map a tensor for CPU access.
 *
 * This function maps the tensor's memory for CPU read/write operations.
 * For DMA tensors, this includes automatic cache synchronization.
 * The returned map must be unmapped with hal_tensor_map_unmap() when done.
 *
 * @param tensor Tensor handle
 * @return Tensor map handle on success, NULL on error
 * @par Errors (errno):
 * - EINVAL: NULL tensor
 * - EIO: Failed to map tensor memory
 */
struct hal_tensor_map *hal_tensor_map_create(const struct hal_tensor *tensor);

/**
 * Get a mutable pointer to the mapped tensor data.
 *
 * The returned pointer is valid only while the map exists.
 * Cast the void* to the appropriate type based on hal_tensor_dtype().
 *
 * @param map Tensor map handle
 * @return Pointer to data, or NULL if map is NULL
 */
void *hal_tensor_map_data(struct hal_tensor_map *map);

/**
 * Get a const pointer to the mapped tensor data.
 *
 * The returned pointer is valid only while the map exists.
 * Cast the void* to the appropriate type based on hal_tensor_dtype().
 *
 * @param map Tensor map handle
 * @return Pointer to data, or NULL if map is NULL
 */
const void *hal_tensor_map_data_const(const struct hal_tensor_map *map);

/**
 * Get the shape of a mapped tensor.
 *
 * @param map Tensor map handle
 * @param out_ndim Output parameter for number of dimensions (can be NULL)
 * @return Pointer to shape array, or NULL if map is NULL
 */
const size_t *hal_tensor_map_shape(const struct hal_tensor_map *map, size_t *out_ndim);

/**
 * Get the total number of elements in a mapped tensor.
 *
 * @param map Tensor map handle
 * @return Number of elements, or 0 if map is NULL
 */
size_t hal_tensor_map_len(const struct hal_tensor_map *map);

/**
 * Get the total size in bytes of mapped tensor data.
 *
 * @param map Tensor map handle
 * @return Size in bytes, or 0 if map is NULL
 */
size_t hal_tensor_map_size(const struct hal_tensor_map *map);

/**
 * Unmap a tensor and release the mapping.
 *
 * For DMA tensors, this includes automatic cache synchronization.
 * After calling this function, the map pointer becomes invalid.
 *
 * @param map Tensor map handle to unmap (can be NULL, no-op)
 */
void hal_tensor_map_unmap(struct hal_tensor_map *map);

/**
 * Create a new ByteTrack tracker with specified parameters.
 *
 * @param track_thresh Score threshold for creating new tracks
 * @param high_thresh High confidence threshold for first-pass matching
 * @param match_thresh IOU threshold for matching detections to tracks
 * @param frame_rate Expected frame rate of the input video
 * @param track_buffer Number of frames to keep lost tracks before deletion
 * @return New ByteTrack handle on success, NULL on error
 * @par Errors (errno):
 * - ENOMEM: Memory allocation failed
 */
struct hal_bytetrack *hal_bytetrack_new(float track_thresh,
                                        float high_thresh,
                                        float match_thresh,
                                        int frame_rate,
                                        int track_buffer);

/**
 * Create a new ByteTrack tracker with default parameters.
 *
 * Default values:
 * - track_thresh: 0.25
 * - high_thresh: 0.7
 * - match_thresh: 0.25
 * - track_extra_lifespan: 500ms
 *
 * @return New ByteTrack handle on success, NULL on error
 * @par Errors (errno):
 * - ENOMEM: Memory allocation failed
 */
struct hal_bytetrack *hal_bytetrack_new_default(void);

/**
 * Update the tracker with new detections.
 *
 * @param tracker ByteTrack handle
 * @param detections Detection box list from decoder
 * @param timestamp Current timestamp in nanoseconds
 * @return Track info list with updated tracks (caller must free), NULL on error
 * @par Errors (errno):
 * - EINVAL: Invalid argument (NULL tracker/detections)
 */
struct hal_track_info_list *hal_bytetrack_update(struct hal_bytetrack *tracker,
                                                 const struct hal_detect_box_list *detections,
                                                 uint64_t timestamp);

/**
 * Get all currently active tracks.
 *
 * @param tracker ByteTrack handle
 * @return Track info list (caller must free), NULL on error
 * @par Errors (errno):
 * - EINVAL: Invalid argument (NULL tracker)
 */
struct hal_track_info_list *hal_bytetrack_get_active_tracks(const struct hal_bytetrack *tracker);

/**
 * Free a ByteTrack tracker.
 *
 * @param tracker ByteTrack handle to free (can be NULL, no-op)
 */
void hal_bytetrack_free(struct hal_bytetrack *tracker);

/**
 * Get the number of tracks in a list.
 *
 * @param list Track info list handle
 * @return Number of tracks, or 0 if list is NULL
 */
size_t hal_track_info_list_len(const struct hal_track_info_list *list);

/**
 * Get a track info from a list by index.
 *
 * @param list Track info list handle
 * @param index Index of the track (0-based)
 * @param out_info Output parameter for the track info
 * @return 0 on success, -1 on error
 * @par Errors (errno):
 * - EINVAL: Invalid argument (NULL list/out_info, index out of bounds)
 */
int hal_track_info_list_get(const struct hal_track_info_list *list,
                            size_t index,
                            struct hal_track_info *out_info);

/**
 * Free a track info list.
 *
 * @param list Track info list handle to free (can be NULL, no-op)
 */
void hal_track_info_list_free(struct hal_track_info_list *list);

/**
 * Convert a UUID byte array to a string representation.
 *
 * The output buffer must be at least 37 bytes (36 chars + null terminator).
 *
 * @param uuid UUID byte array (16 bytes)
 * @param out_str Output buffer for string representation
 * @param out_len Size of output buffer
 * @return 0 on success, -1 on error
 * @par Errors (errno):
 * - EINVAL: Invalid argument (NULL pointers, buffer too small)
 */
int hal_uuid_to_string(const uint8_t (*uuid)[16], char *out_str, size_t out_len);

#ifdef __cplusplus
}
#endif

#endif /* EDGEFIRST_HAL_H */
