//! Minimal OpenGL ES bindings for the EdgeFirst HAL.
//!
//! This crate is a trimmed, maintained fork of [`gls`](https://github.com/vaxpl/gls-rs)
//! by Varphone Wong, which became unmaintained. Only the surface the HAL uses is
//! kept: the raw `gl` bindings (generated by `gl_generator`), a small set of safe
//! wrappers, and the `Error` type. The upstream higher-level helpers (textures,
//! framebuffers, shaders, buffers, math types) and their `nalgebra`/`serde`
//! dependencies have been dropped, leaving no runtime dependencies.
//!
//! It is published as `edgefirst-gl` and imported as `edgefirst_gl`.

/// Foreign Function Interface of the OpenGL ES bindings (generated by `gl_generator`).
pub mod gl;
pub use gl::{load_with, GLchar, GLeglImageOES, GLenum, GLint, GLsizei, GLuint};

/// Error object for OpenGL.
pub mod error;
pub use error::Error;

/// Safe-ish wrappers over the raw bindings.
pub mod apis;
pub use apis::*;
